name: semgrep-rules-test-historical
on:
  pull_request:
    branches:
    - develop
    - release
  push:
    branches:
    - develop
    - release
jobs:
  test-historical:
    name: rules-test-historical
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: semgrep-rules
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9.2
    # need to delete these directories or else we get linter errors during 
    # the "validate" step.
    - name: install semgrep
      run: pip3 install semgrep
    - name: delete stats directory
      run: rm -rf semgrep-rules/stats
    - name: delete fingerprints directory
      run: rm -rf semgrep-rules/fingerprints
    - name: grab historical semgrep version
      run: |
        SEMGREP_VERSION=`semgrep --version`
        SEMGREP_VERSION_SHORT=${SEMGREP_VERSION:2:2}
        SEMGREP_OLD_VERSION="0.$(($SEMGREP_VERSION_SHORT-3)).0"
        echo "SEMGREP_OLD_VERSION=$SEMGREP_OLD_VERSION" >> $GITHUB_ENV
    - name: validate rules on historical semgrep version
      run: |
        docker run --rm -v ${GITHUB_WORKSPACE}/semgrep-rules:/src returntocorp/semgrep:${SEMGREP_OLD_VERSION} semgrep --validate --config /src
    - name: test with historical semgrep version
      run: |
        docker run --rm -v ${GITHUB_WORKSPACE}/semgrep-rules:/src returntocorp/semgrep:${SEMGREP_OLD_VERSION} semgrep --test --test-ignore-todo /src
